### PR TITLE
Extend X-RTP-Stat header information

### PR DESCRIPTION
**Pull request by negbie**
For more information in detail please take a look here:
https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/xrtpv32.pdf

### CODE REVIEW

**Comment by lmangani** [comment]
Thanks for your contribution! Please if not already done, sign our Contributor License Agreement
http://cla.qxip.net

**Comment by negbie** [comment]
Hi Lorenzo,

done so!

**Comment by adubovikov** [comment]
thank you!

**Comment by lmangani** [comment]
@negbie any chance you can provide a sample we can use to add this test to HEPGEN?

**Comment by negbie** [comment]
@lmangani, sure i will send you tomorrow an pcap and extend your hepgen.js/config/default.js with an correspondingly bye message.

**Comment by lmangani** [comment]
Thanks in advance! The ideal config to plan custom media reports at this time is https://github.com/sipcapture/hepgen.js/blob/master/config/b2bcall_rtcp.js (or feel free to create a new one, too)

**Pull request merged**
