### PR TITLE
Fix partial match of ip address in alias

### PR DESCRIPTION
**Pull request by Den4t**
This is fix inccorrect connections in flow view, when hosts ip's are partialy matched, f.e. 192.168.49.1 and 192.168.49.175.

Screenshot_20200702_201238

### CODE REVIEW

**Comment by mikegoodstadt** [comment]
I have to redirected the merge to devel rather than master to ensure review process.

**Comment by Den4t** [comment]
No, i do not test with IPv6.

**Comment by Den4t** [comment]
I do not have IPv6 addressing on my net, so can't test, but if i right understand the problem in different ipv6 address:port notation,
can be [ADDR]:PORT and ADDR:PORT, how about this:
const __alias = Object.entries(this.dataItem.data.alias).find(j => (j[0].startsWith(i+':') || j[0].startsWith('['+i+']'+':')));

**Comment by jacovinus** [comment]
@Den4t good approach!  we will be testing it in different scenarios and then give you feedback :+1:

**Comment by systemcrash** [comment]
> I do not have IPv6 addressing on my net, so can't test, but if i right understand the problem in different ipv6 address:port notation,
> can be [ADDR]:PORT and ADDR:PORT, how about this:
> const __alias = Object.entries(this.dataItem.data.alias).find(j => (j[0].startsWith(i+':') || j[0].startsWith('['+i+']'+':')));

What happens to an IPv6 address which does not contain `[` or `]` ? ( recommend the above code is tested on both variants of an IPv6. Below libraries exhibit many test-cases for both IP families )

The approach I chose in #227 and #230 ( and #258 ) was to work *backwards* from the end of the IPv6 (after finding the :port part). This is if you want to avoid using an extra library which will make life simpler: e.g.:

https://github.com/indutny/node-ip 

this one supports e.g.
```
ip.isV4Format('127.0.0.1'); // true
ip.isV6Format('::ffff:127.0.0.1'); // true
```

https://github.com/whitequark/ipaddr.js
https://github.com/beaugunderson/ip-address

I recommend this approach in general since in the future there will be newer IP families, and one can do simpler queries like
addr.isipv6 instead of relying on complex regexp. It also opens up possibilities to do sorting correctly :)

**Comment by jacovinus** [comment]
Thank you very much for your contribution @systemcrash. we will be taking a look a that too.

**Comment by jacovinus** [comment]
@systemcrash the PR that @Den4t is making solves IPV4 aliasing in subnets. 

We are working on new issue for IPV6 , and will tag you on there to give it a try.

**Pull request merged**
