### PR TITLE
Additional agent and gateway images

### PR DESCRIPTION
**Pull request by t1mb0**

### CODE REVIEW

**Comment by lmangani** [comment]
Tim,

I don't think we can distribute those copyrighted logos with our OSS application. I will keep this on hold.

**Comment by t1mb0** [comment]
Funny I actually thought this upon submission..assume the pictures of the actual devices are OK? If so may make up a few more.

**Comment by lmangani** [comment]
I think the way to go is to let users feed from an external/web repository where those can be hosted separately from our application code. We will return with some options briefly, your contribution is nevertheless much appreciated. Please do not forget to sign our CLA (http://cla.qxip.net)

**Comment by adubovikov** [comment]
http://www.cisco.com/web/about/ac50/ac47/cisco_logo_program.html

we need make submit request to get permission use cisco's logo. Same for
Polycom and Yealinks

**Comment by lmangani** [comment]
As anticipated, No-Go to include or distribute trademarked logos in our OSS project.
If anyone is willing to contribute artwork/icons resembling the devices without trademarked material we will be happy to consider it for inclusion.

**Comment by t1mb0** [comment]
Not a prob, leave it with me!

**Pull request closed without merging**
